"""Add preview_img field to papers table

Revision ID: 07b700f497ab
Revises: 4b24e6aa5243
Create Date: 2025-08-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b700f497ab'
down_revision = '7901550f2be3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    
    connection = op.get_bind()
    inspector = inspect(connection)
    
    # 檢查 papers 表是否存在
    if 'papers' in inspector.get_table_names():
        existing_columns = [col['name'] for col in inspector.get_columns('papers')]
        
        with op.batch_alter_table('papers', schema=None) as batch_op:
            # 添加預覽圖片字段
            if 'preview_img' not in existing_columns:
                batch_op.add_column(sa.Column('preview_img', sa.String(500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_column('preview_img')
    # ### end Alembic commands ###