"""Add carousel images to lab table

Revision ID: 1681ad61f813
Revises: 
Create Date: 2025-08-09 23:25:01.593561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1681ad61f813'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carousel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_carousel_created_at'))
        batch_op.drop_index(batch_op.f('ix_carousel_enable'))
        batch_op.drop_index(batch_op.f('ix_carousel_enable_order'))
        batch_op.drop_index(batch_op.f('ix_carousel_order_priority'))

    op.drop_table('carousel')
    with op.batch_alter_table('lab', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carousel_img_1', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('carousel_img_2', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('carousel_img_3', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('carousel_img_4', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab', schema=None) as batch_op:
        batch_op.drop_column('carousel_img_4')
        batch_op.drop_column('carousel_img_3')
        batch_op.drop_column('carousel_img_2')
        batch_op.drop_column('carousel_img_1')

    op.create_table('carousel',
    sa.Column('carousel_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title_zh', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('title_en', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('description_zh', mysql.TEXT(), nullable=True),
    sa.Column('description_en', mysql.TEXT(), nullable=True),
    sa.Column('image_path', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('link_url', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('order_priority', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('enable', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('carousel_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('carousel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_carousel_order_priority'), ['order_priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_carousel_enable_order'), ['enable', 'order_priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_carousel_enable'), ['enable'], unique=False)
        batch_op.create_index(batch_op.f('ix_carousel_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###
