"""Add carousel images to lab table

Revision ID: 1681ad61f813
Revises: 
Create Date: 2025-08-09 23:25:01.593561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1681ad61f813'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 檢查 carousel 表是否存在，如果存在則刪除
    from sqlalchemy import inspect
    from sqlalchemy.engine import reflection
    
    connection = op.get_bind()
    inspector = inspect(connection)
    
    # 如果 carousel 表存在，則執行刪除操作
    if 'carousel' in inspector.get_table_names():
        try:
            with op.batch_alter_table('carousel', schema=None) as batch_op:
                batch_op.drop_index(batch_op.f('ix_carousel_created_at'))
                batch_op.drop_index(batch_op.f('ix_carousel_enable'))
                batch_op.drop_index(batch_op.f('ix_carousel_enable_order'))
                batch_op.drop_index(batch_op.f('ix_carousel_order_priority'))
            
            op.drop_table('carousel')
        except Exception as e:
            # 如果刪除失敗，可能是索引不存在，忽略錯誤
            print(f"Warning: Failed to drop carousel table or indexes: {e}")
    
    # 添加 carousel 圖片字段到 lab 表
    with op.batch_alter_table('lab', schema=None) as batch_op:
        # 檢查列是否已存在，避免重複添加
        existing_columns = [col['name'] for col in inspector.get_columns('lab')]
        
        if 'carousel_img_1' not in existing_columns:
            batch_op.add_column(sa.Column('carousel_img_1', sa.String(length=500), nullable=True))
        if 'carousel_img_2' not in existing_columns:
            batch_op.add_column(sa.Column('carousel_img_2', sa.String(length=500), nullable=True))
        if 'carousel_img_3' not in existing_columns:
            batch_op.add_column(sa.Column('carousel_img_3', sa.String(length=500), nullable=True))
        if 'carousel_img_4' not in existing_columns:
            batch_op.add_column(sa.Column('carousel_img_4', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab', schema=None) as batch_op:
        batch_op.drop_column('carousel_img_4')
        batch_op.drop_column('carousel_img_3')
        batch_op.drop_column('carousel_img_2')
        batch_op.drop_column('carousel_img_1')

    op.create_table('carousel',
    sa.Column('carousel_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title_zh', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('title_en', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('description_zh', mysql.TEXT(), nullable=True),
    sa.Column('description_en', mysql.TEXT(), nullable=True),
    sa.Column('image_path', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('link_url', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('order_priority', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('enable', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('carousel_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('carousel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_carousel_order_priority'), ['order_priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_carousel_enable_order'), ['enable', 'order_priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_carousel_enable'), ['enable'], unique=False)
        batch_op.create_index(batch_op.f('ix_carousel_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###
