"""Add lab_resource table

Revision ID: 201331d635c5
Revises: 07b700f497ab
Create Date: 2025-08-15 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201331d635c5'
down_revision = '07b700f497ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    
    connection = op.get_bind()
    inspector = inspect(connection)
    
    # 檢查 lab_resource 表是否存在
    if 'lab_resource' not in inspector.get_table_names():
        op.create_table('lab_resource',
            sa.Column('resource_id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('resource_name_zh', sa.String(200), nullable=False),
            sa.Column('resource_name_en', sa.String(200), nullable=True),
            sa.Column('resource_description_zh', sa.Text(), nullable=True),
            sa.Column('resource_description_en', sa.Text(), nullable=True),
            sa.Column('resource_type', sa.Integer(), nullable=False, default=0),
            sa.Column('resource_location_zh', sa.String(300), nullable=True),
            sa.Column('resource_location_en', sa.String(300), nullable=True),
            sa.Column('resource_url', sa.String(500), nullable=True),
            sa.Column('resource_file', sa.String(500), nullable=True),
            sa.Column('resource_image', sa.String(500), nullable=True),
            sa.Column('availability_status', sa.Integer(), nullable=False, default=1),
            sa.Column('contact_info', sa.String(200), nullable=True),
            sa.Column('created_time', sa.DateTime(), nullable=False, default=sa.func.current_timestamp()),
            sa.Column('updated_time', sa.DateTime(), nullable=False, default=sa.func.current_timestamp()),
            sa.PrimaryKeyConstraint('resource_id')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lab_resource')
    # ### end Alembic commands ###