"""Add uploaded_image table for markdown description images

Revision ID: 7901550f2be3
Revises: add_news_title_fields
Create Date: 2025-08-14 05:19:37.913425

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '7901550f2be3'
down_revision = 'add_news_title_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_images',
        sa.Column('image_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('filename', sa.String(length=255), nullable=False),
        sa.Column('file_path', sa.String(length=500), nullable=False),
        sa.Column('file_url', sa.String(length=500), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=False),
        sa.Column('mime_type', sa.String(length=100), nullable=False),
        sa.Column('entity_type', sa.String(length=50), nullable=True),
        sa.Column('entity_id', sa.Integer(), nullable=True),
        sa.Column('field_name', sa.String(length=100), nullable=True),
        sa.Column('is_used', sa.Boolean(), nullable=False),
        sa.Column('used_at', sa.DateTime(), nullable=True),
        sa.Column('uploaded_by', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('image_id'),
        sa.UniqueConstraint('file_path')
    )
    with op.batch_alter_table('uploaded_images', schema=None) as batch_op:
        batch_op.create_index('ix_uploaded_images_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_uploaded_images_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_uploaded_images_entity_id', ['entity_id'], unique=False)
        batch_op.create_index('ix_uploaded_images_entity_type', ['entity_type'], unique=False)
        batch_op.create_index('ix_uploaded_images_is_used', ['is_used'], unique=False)
        batch_op.create_index('ix_uploaded_images_unused', ['is_used', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_images', schema=None) as batch_op:
        batch_op.drop_index('ix_uploaded_images_unused')
        batch_op.drop_index('ix_uploaded_images_is_used')
        batch_op.drop_index('ix_uploaded_images_entity_type')
        batch_op.drop_index('ix_uploaded_images_entity_id')
        batch_op.drop_index('ix_uploaded_images_entity')
        batch_op.drop_index('ix_uploaded_images_created_at')
    
    op.drop_table('uploaded_images')
    # ### end Alembic commands ###