"""Add title fields to news table

Revision ID: 8b7db43fe61e
Revises: 4b24e6aa5243
Create Date: 2025-01-14 03:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b7db43fe61e'
down_revision = '4b24e6aa5243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    
    connection = op.get_bind()
    inspector = inspect(connection)
    
    # 檢查 news 表是否存在
    if 'news' in inspector.get_table_names():
        existing_columns = [col['name'] for col in inspector.get_columns('news')]
        existing_indexes = [idx['name'] for idx in inspector.get_indexes('news')]
        
        with op.batch_alter_table('news', schema=None) as batch_op:
            if 'news_title_zh' not in existing_columns:
                batch_op.add_column(sa.Column('news_title_zh', sa.String(length=500), nullable=True))
            if 'news_title_en' not in existing_columns:
                batch_op.add_column(sa.Column('news_title_en', sa.String(length=500), nullable=True))
            
            # 創建索引（如果不存在）
            if 'ix_news_title_zh' not in existing_indexes:
                batch_op.create_index('ix_news_title_zh', ['news_title_zh'], unique=False)
            if 'ix_news_title_en' not in existing_indexes:
                batch_op.create_index('ix_news_title_en', ['news_title_en'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_index('ix_news_title_en')
        batch_op.drop_index('ix_news_title_zh')
        batch_op.drop_column('news_title_en')
        batch_op.drop_column('news_title_zh')
    # ### end Alembic commands ###