"""Add all_authors fields to papers table

Revision ID: add_all_authors_fields
Revises: 1681ad61f813
Create Date: 2025-01-14 03:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_all_authors_fields'
down_revision = '1681ad61f813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    
    connection = op.get_bind()
    inspector = inspect(connection)
    
    # 檢查 papers 表是否存在
    if 'papers' in inspector.get_table_names():
        existing_columns = [col['name'] for col in inspector.get_columns('papers')]
        
        with op.batch_alter_table('papers', schema=None) as batch_op:
            if 'all_authors_zh' not in existing_columns:
                batch_op.add_column(sa.Column('all_authors_zh', sa.Text(), nullable=True))
            if 'all_authors_en' not in existing_columns:
                batch_op.add_column(sa.Column('all_authors_en', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_column('all_authors_en')
        batch_op.drop_column('all_authors_zh')
    # ### end Alembic commands ###