"""Add title fields to news table

Revision ID: add_news_title_fields
Revises: add_all_authors_fields
Create Date: 2025-01-14 03:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_news_title_fields'
down_revision = 'add_all_authors_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('news_title_zh', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('news_title_en', sa.String(length=500), nullable=True))
        batch_op.create_index('ix_news_title_zh', ['news_title_zh'], unique=False)
        batch_op.create_index('ix_news_title_en', ['news_title_en'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_index('ix_news_title_en')
        batch_op.drop_index('ix_news_title_zh')
        batch_op.drop_column('news_title_en')
        batch_op.drop_column('news_title_zh')
    # ### end Alembic commands ###